server:
  port : 8087
  servlet:
    encoding:
      force-response:

spring:
    datasource:
          url: jdbc:sqlserver://localhost:1433;databaseName=StockWatcher
          username: sa
          password: Sam2019$
          testOnBorrow: true
          validation-query: SELECT 1

    jpa:
        hibernate.ddl-auto: update

    data:
          jpa:
              repositories:
                          bootstrap-mode: deferred

logging:
        level:
            org:
                hibernate:
                          SQL: DEBUG
                          type:
                              descriptor:
                                        sql:
                                            BasicBinder: TRACE

nse:
   site: "http://www.nse.com.ng/market-data/trading-statistics/equities"
   element: "#Sector"
   api: "http://www.nse.com.ng/REST/api/statistics/equities/"



#spring.data.jpa.repositories.bootstrap-mode=deferred
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
# Hibernate ddl auto (create, create-drop, validate, update)
#http://www.nse.com.ng/REST/api/statistics/equities/?market=&sector=financial+services&orderby=&pageSize=10&pageNo=0