server:
  port : 8087
  servlet:
    encoding:
      force-response: true

spring:
    datasource:
          url: jdbc:sqlserver://localhost:1433;databaseName=StockWatcher
          username: sa
          password: Sam2019$
          testOnBorrow: true
          validation-query: SELECT 1

    jpa:
        hibernate.ddl-auto: update

    data:
          jpa:
              repositories:
                          bootstrap-mode: deferred

logging:
        level:
            org:
                hibernate:
                          SQL: DEBUG
                          type:
                              descriptor:
                                        sql:
                                            BasicBinder: TRACE

nse:
   site: "http://www.nse.com.ng/market-data/trading-statistics/equities"
   sectorElement: "#Sector"
   equityApiBaseUrl: "http://www.nse.com.ng/REST/api/statistics/equities/"
   equityApiParameter: "?market=&sector=sectorParameter&orderby=&pageSize=100&pageNo=0"