server:
  port : 8087

spring:
    datasource:
          url: jdbc:sqlserver://localhost:1433;databaseName=StockWatcherClone
          username: sa
          password: Sam2019$
          testOnBorrow: true
          validation-query: SELECT 1

    jpa:
        hibernate.ddl-auto: update

logging:
        level:
            org:
                hibernate:
                          SQL: DEBUG
                          type:
                              descriptor:
                                        sql:
                                            BasicBinder: TRACE



#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
# Hibernate ddl auto (create, create-drop, validate, update)